daemonset:
  # Annotations to apply to the daemonset
  annotations: {}
  # additionals labels
  labels: {}
  affinity: {}
  # Include the daemonset
  enabled: true

  # Allocate smaller chunks of memory per pod.
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
      # output.elasticsearch:
      #   host: '${NODE_NAME}'
      #   hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'           
      output.logstash:
        hosts: ['logstash-logstash:5044']

  resources:
    requests:
      cpu: "100m"
      memory: "100M"
    limits:
      cpu: "500m"
      memory: "200Mi"

  maxUnavailable: