replicas: 2

# Permit co-located instances for kubernetes in docker-dektop.
antiAffinity: "soft"

# Shrink default JVM heap.
esJavaOpts: "-Xmx1024m -Xms1024m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "800m"
    memory: "1500Mi"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi

maxUnavailable: 