logstashConfig:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch-master:9200" ]

logstashPipeline:
  logstash.conf: |
      input {
        beats {
            port => "5044"
        }
      }
      output {
        elasticsearch {
            hosts => ["http://elasticsearch-master:9200"]
        }
      }

persistence:
  enabled: true
  annotations: {}

antiAffinity: "soft"
maxUnavailable:

service:
  annotations: {}
  type: ClusterIP
  loadBalancerIP: ""
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080